name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: "latest"
          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=1 --timeout=3m0s --tests=false --no-config --max-issues-per-linter=4095 --max-same-issues=1023 --disable-all --enable=errcheck --enable=gosimple --enable=govet --enable=ineffassign --enable=staticcheck --enable=typecheck --enable=unused --enable=bodyclose --enable=dogsled --enable=goconst --enable=gofmt --enable=goimports --enable=goprintffuncname --enable=gosec --enable=misspell --enable=nakedret --enable=prealloc --enable=rowserrcheck --enable=stylecheck --enable=unconvert --enable=unparam --enable=exportloopref --enable=gomodguard --enable=asciicheck --enable=errorlint
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
